name: aquicity
description: Aqui City

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  vrouter: ^1.2.1
  responsive_sizer: ^3.1.1
  provider: ^6.0.5
  video_player: ^2.7.0
  webview_flutter_web: ^0.2.2+1
  webview_flutter: ^4.2.2
  file_picker: ^5.3.3
  datetime_picker_formfield_new: ^2.1.0
  http_parser: ^4.0.2
  dio: ^5.3.2
  intl: ^0.18.1
  achievement_view: ^1.0.1
  cooky: ^2.0.0
  responsive_grid_list: ^1.3.2
  url_launcher: ^6.1.14
  http: ^1.1.0
  custom_qr_generator_2: ^0.2.2
  image_cropper: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/portada.jpg
    - assets/images/DIAPOSITIVA1.PNG
    - assets/logos/dct-logo.png
    - assets/logos/dct-logo2.png
    - assets/icons/favicon.png
    - assets/icons/facebook.png
    - assets/icons/facebook_5968764.png
    - assets/icons/gorjeo.png
    - assets/icons/instagram.png
    - assets/icons/skype.png
    - assets/icons/whatsapp.png
    - assets/icons/youtube.png